### PR TITLE
Use prefab oboe

### PR DESCRIPTION
**Pull request by felipecsl**
https://github.com/google/oboe/pull/814

### CODE REVIEW

**Comment by dturner** [comment]
I tried both `master` and `felipecsl--oboe-prefab` versions and they sounded the same. Video of the `felipecsl--oboe-prefab` one: 

https://photos.app.goo.gl/9J4s93otKGYtzong6

**Comment by dturner** [comment]
Also tried on emulator (Pixel 3 API 29) with same results.

**Comment by felipecsl** [comment]
Let me test it again, maybe something else was off when I tested

**Comment by felipecsl** [comment]
Confirmed that it does indeed sound the same in both branches!

**Pull request merged**
